import type { Topic } from '@/types/content'

const topic: Topic = {
  id: '01b-panorama-quiz',
  title: 'Module 1 Checkpoint: Markets, Instruments & Structure',
  type: 'quiz',
  estimatedMinutes: 17,
  quiz: {
    questions: [
      {
        id: 'q1',
        question: 'Which of the following is classified as a "Soft" commodity?',
        options: ['Crude oil (Brent)', 'Arabica coffee', 'Copper', 'Natural gas'],
        correctIndex: 1,
        explanation: 'Arabica coffee is a tropical agricultural commodity — a Soft. The others are Hard commodities (energy and metals).',
      },
      {
        id: 'q2',
        question: 'What does "ABCD" refer to in commodity trading?',
        options: [
          'A regulatory framework for commodity markets',
          'The four main commodity exchanges (CBOT, LME, ICE, CME)',
          'The four dominant agricultural trading houses (ADM, Bunge, Cargill, Dreyfus)',
          'A risk classification system (A = low risk, D = high risk)',
        ],
        correctIndex: 2,
        explanation: 'ABCD refers to Archer Daniels Midland, Bunge, Cargill, and Louis Dreyfus — the four largest agricultural commodity trading houses.',
      },
      {
        id: 'q3',
        question: 'On the live futures screen, a clearly bullish story breaks. What does the price typically do in the first seconds?',
        options: [
          'It jumps instantly to its new level — markets are efficient',
          'It keeps breathing at the old level for a few seconds, then DRIFTS to the new one',
          'Nothing happens until the next day\u2019s open',
          'It falls first, because news is always priced in already',
        ],
        correctIndex: 1,
        explanation: 'Markets absorb news with a LAG: traders must read, decide and execute. On the course\u2019s live screen the tape breathes for ~3 seconds, then drifts to the published level over up to 35 seconds \u2014 the fast readers position during the lag.',
      },
      {
        id: 'q4',
        question: 'A futures exchange provides three core functions the physical trade depends on. Which of the following is NOT one of them?',
        options: [
          'Price discovery',
          'Risk management',
          'Setting production quotas for origin countries',
          'Acting as buyer and seller of last resort',
        ],
        correctIndex: 2,
        explanation: 'The exchange discovers a transparent price, lets the supply chain transfer price risk, and — because contracts are physically deliverable — stands as buyer/seller of last resort. It does not set production quotas; that is producer-side policy (e.g. OPEC in oil).',
      },
      {
        id: 'q5',
        question: 'The screen spikes $300 in seconds on an UNCONFIRMED frost rumour, then fully retraces within a minute. The lesson?',
        options: [
          'Always chase momentum \u2014 the first move is the true one',
          'Unconfirmed flashes tend to REVERT \u2014 real news drifts to a new level and HOLDS it',
          'The exchange made a pricing error and cancelled the trades',
          'Frost is never bullish for coffee',
        ],
        correctIndex: 1,
        explanation: 'A flash move with no confirmed story behind it is position-driven \u2014 stops, panic, thin books \u2014 and it mean-reverts when the dust settles. Confirmed fundamental news behaves differently: the price drifts to a new level and stays. Distinguishing the two is the first skill of the futures screen.',
      },
      {
        id: 'q6',
        question: 'A market where futures prices are HIGHER than the spot price is said to be in:',
        options: ['Backwardation', 'Contango', 'Equilibrium', 'Liquidation'],
        correctIndex: 1,
        explanation: 'Contango = futures above spot, the "normal" state for storable commodities, reflecting the cost of carry. Backwardation is the opposite: spot above futures.',
      },
      {
        id: 'q7',
        question: 'Spot = $80 and the 6-month forward = $85. What does the $5 premium primarily reflect?',
        options: [
          'The market’s forecast that spot will rise to $85',
          'Bullish speculative sentiment',
          'The cost of carry: storage, insurance and financing for six months',
          'An exchange-imposed minimum price move',
        ],
        correctIndex: 2,
        explanation: 'The contango fallacy: forward prices on storable commodities are not forecasts. Arbitrage pins the forward to spot + cost of carry — if it drifted higher, cash-and-carry traders would sell it straight back down.',
      },
      {
        id: 'q8',
        question: 'Which situation most typically produces BACKWARDATION?',
        options: [
          'Oversupply and full warehouses',
          'A supply disruption creating tight nearby availability',
          'Falling interest rates',
          'Cheap, abundant storage capacity',
        ],
        correctIndex: 1,
        explanation: 'Backwardation (spot above futures) signals tight nearby supply or urgent immediate demand — disruptions, drawdowns, seasonal peaks. Oversupply and cheap storage produce contango instead.',
      },
      {
        id: 'q9',
        question: 'Spot = $100, total storage + financing to delivery = $4, and the 6-month future trades at $107. What is the arbitrage?',
        options: [
          'Buy the future and sell spot short — earn $7',
          'Buy spot, store it, sell the future — lock in ~$3 risk-free',
          'No arbitrage: $107 is within fair value',
          'Buy both spot and the future and wait',
        ],
        correctIndex: 1,
        explanation: 'Fair forward = 100 + 4 = $104. At $107 the future is $3 rich: cash-and-carry — buy spot, pay $4 of carry, deliver at $107 — locks in ~$3/unit regardless of where prices go.',
      },
      {
        id: 'q10',
        question: '(Stretch) Under LME-style "lending rules", what happens when one trader controls a dominant share of deliverable warrants?',
        options: [
          'The trader is banned from the exchange',
          'All their positions are cancelled at the previous settlement price',
          'They are obliged to lend their metal at a capped backwardation premium',
          'The exchange buys their position at market price',
        ],
        correctIndex: 2,
        explanation: 'Lending rules force a dominant long to lend to trapped shorts at a capped premium, letting shorts roll forward at a controlled cost — one of the key exchange interventions that defuse a squeeze.',
      },
      {
        id: 'q11',
        question: 'How many metric tonnes does one ICE-EU Robusta Coffee futures lot represent?',
        options: ['5 MT', '10 MT', '20 MT', '37.5 MT'],
        correctIndex: 1,
        explanation: 'One ICE-EU Robusta lot = 10 metric tonnes, quoted in $/MT. ICE-US Arabica is quoted in ¢/lb with 37,500 lb per lot.',
      },
      {
        id: 'q12',
        question: 'You are SHORT 10 lots of Robusta (100 t) at $4,500/t. The market settles at $4,590/t. Your variation margin cash flow today is:',
        options: ['+$9,000', '−$9,000', '−$900', '+$4,590'],
        correctIndex: 1,
        explanation: 'Short position, price up $90/t × 100 t = $9,000 against you — paid out in cash that day. Daily variation margin is the cash reality of a hedge.',
      },
      {
        id: 'q13',
        question: 'The clearinghouse "guarantee" means:',
        options: [
          'Counterparty credit risk is completely eliminated',
          'The exchange insures your trading losses',
          'Counterparty risk is mutualised and collateralised through margin and a default fund',
          'Only banks can trade futures',
        ],
        correctIndex: 2,
        explanation: 'The clearinghouse stands between buyer and seller and manages risk with initial + variation margin and a mutualised default fund. Risk is mitigated, not abolished — the 2018 Nasdaq Clearing power-market default consumed a chunk of the default fund.',
      },
      {
        id: 'q14',
        question: 'How is the vast majority of commodity futures volume actually closed out?',
        options: [
          'By physical delivery at expiry — futures are delivery contracts, so most positions end in coffee changing hands',
          'By an offsetting trade before expiry — delivery is the rare exception, not the routine',
          'By automatic cash settlement — physical delivery is impossible on commodity futures',
          'By converting the position into an OTC swap at expiry',
        ],
        correctIndex: 1,
        explanation: 'Option A is the tempting one: futures ARE deliverable contracts, and deliveries genuinely happen — Vietnamese exporters tendered hundreds of lots in 2024–25 when the FOB differential fell through tenderable parity. But even in that extreme episode, tenders were a tiny fraction of open interest: speculators never want the coffee, and hedgers normally prefer selling their physical through commercial channels. So almost every position is offset before expiry — while delivery’s mere POSSIBILITY (the buyer/seller of last resort) is what anchors the futures price to the physical market. Option C fails the other way: some contracts are cash-settled (Brent, coal, power), but coffee, cotton, sugar and WTI deliver physically if held to expiry.',
      },
      {
        id: 'q15',
        question: 'A trader needs to hedge a 700,000-barrel crude cargo with ICE Brent futures (1,000 bbl/lot). How many lots?',
        options: ['70', '700', '7,000', '1,400'],
        correctIndex: 1,
        explanation: '700,000 ÷ 1,000 = 700 lots. Sizing the hedge to the physical exposure is always the first calculation on the desk.',
      },
      {
        id: 'q16',
        question: 'What is the main advantage of a swap over a futures contract for a commodity producer?',
        options: [
          'No margin calls',
          'Exchange-guaranteed clearing eliminates credit risk',
          'Flexibility in size, tenor, and settlement terms',
          'Lower transaction costs',
        ],
        correctIndex: 2,
        explanation: 'Swaps are OTC and can be customized in size, duration, and settlement — but unlike futures, they carry counterparty credit risk since there is no clearinghouse.',
      },
      {
        id: 'q17',
        question: 'A producer swaps 500 t at a fixed $4,300/t against the monthly index average. The index averages $4,150. Who pays whom?',
        options: [
          'The producer pays $75,000 to the counterparty',
          'The counterparty pays the producer $75,000',
          'No payment — the swap only settles at maturity',
          'The producer delivers 500 t of coffee',
        ],
        correctIndex: 1,
        explanation: 'The producer receives fixed − floating = 4,300 − 4,150 = +$150/t × 500 t = $75,000. Combined with selling their physical at the (low) market price, their effective price stays ~$4,300. Swaps are financially settled — no coffee moves.',
      },
      {
        id: 'q18',
        question: 'Two parties agree to transfer a futures position between them at one agreed price, tied to a physical trade. Why register it as an EFP rather than each trading on the screen?',
        options: [
          'EFPs avoid exchange fees entirely',
          'On-screen trading is prohibited for commercial hedgers',
          'The EFP moves the futures at one agreed price — no legging risk between two separate executions',
          'EFPs settle in physical coffee instead of cash',
        ],
        correctIndex: 2,
        explanation: 'An EFP (Exchange for Physical) is a privately negotiated, exchange-registered transfer of a futures position at an agreed price, done against a physical trade. Both legs crystallise simultaneously — neither party risks the market moving between two separate screen executions.',
      },
    ],
  },
}

export default topic
